[package]
name = "jiff-sqlx-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
jiff = "0.2.1"
jiff-sqlx = { version = "0.1.0", features = ["postgres"] }
sqlx = { version = "0.8.3", features = ["macros", "postgres", "runtime-tokio"] }
tokio = { version = "1.43.0", features = ["full"] }
